# Generated by Django 5.0.6 on 2024-06-20 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mon_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categorie',
            field=models.CharField(choices=[('Football', 'Football'), ('Jeux-Vidéos', 'Jeux-videos'), ('Animés', 'Animes'), ('Autres', 'Autres')], default='Autres', max_length=50),
        ),
    ]
