# Generated by Django 5.0.6 on 2024-06-21 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mon_blog', '0003_post_image_post_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categorie',
            field=models.CharField(choices=[('foot', 'Football'), ('jeu', 'Jeux-video'), ('anime', 'Animes'), ('autre', 'Autres')], default='Autres', max_length=50),
        ),
    ]
