# Generated by Django 5.0.6 on 2024-06-21 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mon_blog', '0004_alter_post_categorie'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotDePasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mdp_hache', models.CharField(max_length=256)),
            ],
        ),
    ]
