# Generated by Django 5.0.6 on 2024-06-21 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mon_blog', '0005_motdepasse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motdepasse',
            name='mdp_hache',
            field=models.CharField(max_length=256, verbose_name='Mot de Passe'),
        ),
    ]
